apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-app-4
  namespace: default
  labels:
    app:  nginx-app-4
spec:
  selector:
    matchLabels:
      app: nginx-app-4
  replicas: 2
  template:
    metadata:
      labels:
        app:  nginx-app-4
    spec:
      containers:
      - name:  nginx
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80