apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-app-5
  namespace: super-app
  labels:
    app:  nginx-app-5
spec:
  selector:
    matchLabels:
      app: nginx-app-5
  replicas: 1
  template:
    metadata:
      labels:
        app:  nginx-app-5
    spec:
      containers:
      - name:  nginx
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
        