apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  my-app-5
  namespace: argocd
  finalizers:
  - resource-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-apps-5
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my-app/app-5
    repoURL: https://github.com/006362/argocd-app-of-app.git
    tragetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true