apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  my-app-3
  namespace: argocd
  finalizers:
  - resource-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-apps-3
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my-app/app-3
    repoURL: https://github.com/006362/argocd-app-of-app.git
    tragetRevision: HEAD